apiVersion: v1
kind: Pod
metadata:
  name: openstack-cli
  namespace: openstack
spec:
  restartPolicy: Never
  containers:
    - name: cli
      image: ubuntu:22.04
      command: ["/bin/bash", "-c"]
      args:
        - |
          apt update && \
          DEBIAN_FRONTEND=noninteractive apt install -y python3-openstackclient curl && \
          mkdir -p /root && \
          cat > /root/openrc << 'EOF'
          export OS_IDENTITY_API_VERSION=3
          export OS_AUTH_URL=http://keystone-api.openstack.svc.cluster.local:5000/v3
          export OS_AUTH_TYPE=password
          export OS_REGION_NAME=RegionOne
          export OS_USER_DOMAIN_NAME=Default
          export OS_USERNAME=admin-RegionOne
          export OS_PASSWORD=VmnnRGnSVEqGevSMBixzx1vddqMVvc1l
          export OS_PROJECT_DOMAIN_NAME=Default
          export OS_PROJECT_NAME=admin
          EOF
          echo "CLI ready. Sleeping..." && sleep infinity
      tty: true
      stdin: true
