# Copyright 2026 Kezie Iwueke
# SPDX-License-Identifier: Apache-2.0

# src/daalu/helm/interface.py
from typing import Protocol
from ..config.models import RepoSpec, ReleaseSpec

class IHelm(Protocol):
    """Abstract Helm client boundary. Implementations can be CLI or Template+Apply."""
    def add_repo(self, repo: RepoSpec) -> None: ...
    def update_repos(self) -> None: ...
    def upgrade_install(self, rel: ReleaseSpec) -> None: ...
    def release_is_deployed(self, release_name: str, namespace: str) -> bool: ...
    def uninstall(self, release_name: str, namespace: str) -> None: ...
    def diff(self, rel: ReleaseSpec) -> str: ...
    def lint(self, rel: ReleaseSpec) -> None: ...
