#!/usr/bin/env bash
# =============================================================================
# Daalu Secrets Generator
# =============================================================================
# Generates a complete cloud-config/secrets.yaml with random credentials.
#
# Usage:
#   ./scripts/generate-secrets.sh
#   ./scripts/generate-secrets.sh --output /path/to/secrets.yaml
#
# Fields that require user input (SSH keys, host IPs, etc.) are left as
# placeholders that you MUST fill in after generation.
# =============================================================================

set -euo pipefail

OUTPUT="${1:-cloud-config/secrets.yaml}"

# Resolve relative to repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ "$OUTPUT" != /* ]]; then
    OUTPUT="$REPO_ROOT/$OUTPUT"
fi

if [[ -f "$OUTPUT" ]]; then
    echo "WARNING: $OUTPUT already exists."
    read -rp "Overwrite? [y/N] " confirm
    if [[ "$confirm" != [yY] ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
rand_password() {
    openssl rand -base64 24 | tr -d '/+=' | head -c 32
}

rand_base64() {
    openssl rand -base64 "$1"
}

rand_hex() {
    openssl rand -hex "$1"
}

# Generate a random password for image_password and its hash
IMAGE_PASSWORD="$(rand_password)"
IMAGE_PASSWORD_HASH="$(openssl passwd -6 "$IMAGE_PASSWORD")"

# Generate SSH keypair for manila and nova if ssh-keygen is available
generate_ssh_key() {
    local tmpfile
    tmpfile=$(mktemp)
    rm -f "$tmpfile" "${tmpfile}.pub"
    ssh-keygen -t rsa -b 4096 -f "$tmpfile" -N "" -q
    cat "$tmpfile"
    rm -f "$tmpfile" "${tmpfile}.pub"
}

MANILA_SSH_KEY="$(generate_ssh_key)"
NOVA_SSH_KEY="$(generate_ssh_key)"

# ---------------------------------------------------------------------------
# Write secrets.yaml
# ---------------------------------------------------------------------------
cat > "$OUTPUT" << SECRETS_EOF
# =============================================================================
# Daalu Secrets
# =============================================================================
# Auto-generated by scripts/generate-secrets.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# NEVER commit this file to version control.
# =============================================================================

# ---------------------------------------------------------------------------
# Cluster API / Proxmox credentials
# ---------------------------------------------------------------------------
# IMPORTANT: Fill in the placeholders below with your actual values.
cluster_api:
  builder_password: "$(rand_password)"
  image_password: "$IMAGE_PASSWORD"
  image_password_hash: "$IMAGE_PASSWORD_HASH"
  ssh_public_key: "<PASTE-YOUR-SSH-PUBLIC-KEY-HERE>"
  ssh_public_key_path: "~/.ssh/openstack-key.pub"
  proxmox_url: "https://<PROXMOX-HOST>:8006"
  proxmox_token: "root@pam!<TOKEN-NAME>"
  proxmox_secret: "<PROXMOX-API-TOKEN-SECRET>"
  mgmt_host: "<MANAGEMENT-HOST-IP>"
  mgmt_user: "<MANAGEMENT-SSH-USER>"

# ---------------------------------------------------------------------------
# Keycloak (identity provider)
# ---------------------------------------------------------------------------
keycloak:
  monitoring:
    password: "$(rand_password)"
  openstack:
    password: "$(rand_password)"
    github_token: "<GITHUB-PERSONAL-ACCESS-TOKEN>"

# ---------------------------------------------------------------------------
# Monitoring — Thanos / MinIO object storage
# ---------------------------------------------------------------------------
monitoring:
  thanos:
    access_key: "$(rand_password)"
    secret_key: "$(rand_password)"

# ---------------------------------------------------------------------------
# OpenStack Helm endpoint passwords & component secrets
# ---------------------------------------------------------------------------
openstack_secrets:
  barbican_key: "$(rand_base64 32)"
  heat_auth_encryption_key: "$(rand_password)"
  keepalived_password: "$(rand_password)"
  keycloak_admin_password: "$(rand_password)"
  keycloak_database_password: "$(rand_password)"
  keystone_keycloak_client_secret: "$(rand_password)"
  keystone_oidc_crypto_passphrase: "$(rand_password)"
  kube_prometheus_stack_grafana_admin_password: "$(rand_password)"
  manila_ssh_key: |
$(echo "$MANILA_SSH_KEY" | sed 's/^/    /')
  nova_ssh_key: |
$(echo "$NOVA_SSH_KEY" | sed 's/^/    /')
  octavia_heartbeat_key: "$(rand_password)"
  barbican_keystone_password: "$(rand_password)"
  barbican_mariadb_password: "$(rand_password)"
  cinder_keystone_password: "$(rand_password)"
  cinder_mariadb_password: "$(rand_password)"
  cinder_rabbitmq_password: "$(rand_password)"
  designate_keystone_password: "$(rand_password)"
  designate_mariadb_password: "$(rand_password)"
  designate_rabbitmq_password: "$(rand_password)"
  glance_keystone_password: "$(rand_password)"
  glance_mariadb_password: "$(rand_password)"
  glance_rabbitmq_password: "$(rand_password)"
  heat_keystone_password: "$(rand_password)"
  heat_mariadb_password: "$(rand_password)"
  heat_rabbitmq_password: "$(rand_password)"
  heat_stack_user_keystone_password: "$(rand_password)"
  heat_trustee_keystone_password: "$(rand_password)"
  horizon_mariadb_password: "$(rand_password)"
  ironic_keystone_password: "$(rand_password)"
  ironic_mariadb_password: "$(rand_password)"
  ironic_rabbitmq_password: "$(rand_password)"
  keystone_admin_password: "$(rand_password)"
  keystone_mariadb_password: "$(rand_password)"
  keystone_rabbitmq_password: "$(rand_password)"
  magnum_keystone_password: "$(rand_password)"
  magnum_mariadb_password: "$(rand_password)"
  magnum_rabbitmq_password: "$(rand_password)"
  manila_keystone_password: "$(rand_password)"
  manila_mariadb_password: "$(rand_password)"
  memcached_secret_key: "$(rand_password)"
  neutron_keystone_password: "$(rand_password)"
  neutron_mariadb_password: "$(rand_password)"
  neutron_metadata_secret: "$(rand_password)"
  neutron_rabbitmq_password: "$(rand_password)"
  nova_keystone_password: "$(rand_password)"
  nova_mariadb_password: "$(rand_password)"
  nova_rabbitmq_password: "$(rand_password)"
  octavia_keystone_password: "$(rand_password)"
  octavia_mariadb_password: "$(rand_password)"
  octavia_rabbitmq_password: "$(rand_password)"
  openstack_exporter_keystone_password: "$(rand_password)"
  placement_keystone_password: "$(rand_password)"
  placement_mariadb_password: "$(rand_password)"
  rabbitmq_admin_password: "$(rand_password)"
  rgw_keystone_password: "$(rand_password)"
  staffeln_mariadb_password: "$(rand_password)"
  tempest_keystone_password: "$(rand_password)"
  github_token: "<GITHUB-PERSONAL-ACCESS-TOKEN>"
SECRETS_EOF

chmod 600 "$OUTPUT"

echo ""
echo "Secrets file generated: $OUTPUT"
echo ""
echo "IMPORTANT: You must fill in these placeholders before deploying:"
echo "  - cluster_api.ssh_public_key"
echo "  - cluster_api.ssh_public_key_path"
echo "  - cluster_api.proxmox_url"
echo "  - cluster_api.proxmox_token"
echo "  - cluster_api.proxmox_secret"
echo "  - cluster_api.mgmt_host"
echo "  - cluster_api.mgmt_user"
echo "  - keycloak.openstack.github_token"
echo "  - openstack_secrets.github_token"
echo ""
