apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: auto-openstack-infra
  namespace: metal3
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.201.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiGroup: controlplane.cluster.x-k8s.io
    kind: KubeadmControlPlane
    name: auto-openstack-infra
  infrastructureRef:
    apiGroup: infrastructure.cluster.x-k8s.io
    kind: Metal3Cluster
    name: auto-openstack-infra
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: auto-openstack-infra
  namespace: metal3
spec:
  controlPlaneEndpoint:
    host: 192.168.0.249
    port: 6443
  noCloudProvider: true
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: provisioning-pool
  namespace: metal3
spec:
  clusterName: auto-openstack-infra
  namePrefix: auto-openstack-infra-prov
  pools:
  - end: 172.22.0.200
    start: 172.22.0.100
  prefix: 24
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: externalv4-pool
  namespace: metal3
spec:
  clusterName: auto-openstack-infra
  gateway: 192.168.0.1
  namePrefix: auto-openstack-infra-bmv4
  pools:
  - end: 192.168.111.40
    start: 192.168.111.20
  prefix: 24
