apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: auto-openstack-infra
  namespace: metal3
spec:
  kubeadmConfigSpec:
    files:
    - content: |
        ! Configuration File for keepalived

        vrrp_script k8s_api_check {
            script "curl -sk https://127.0.0.1:6443/healthz"
            interval 5
            timeout 5
            rise 3
            fall 3
        }

        vrrp_instance VI_2 {
            state MASTER
            interface eno2

            virtual_router_id 2
            priority 101
            advert_int 1
            virtual_ipaddress {
                192.168.0.249
            }
            track_script {
                k8s_api_check
            }
        }
      path: /etc/keepalived/keepalived.conf
    - content: |
        network:
          version: 2
          renderer: networkd
          bridges:
            provisioning:
              interfaces: [eno1]
              addresses:
              - {{ ds.meta_data.provisioningIP }}/{{ ds.meta_data.provisioningCIDR }}
      owner: root:root
      path: /etc/netplan/52-ironicendpoint.yaml
      permissions: "0600"
    - content: |
        [registries.search]
        registries = ['docker.io']

        [registries.insecure]
        registries = ['192.168.111.1:5000']
      path: /etc/containers/registries.conf
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
        - name: node-labels
          value: metal3.io/uuid={{ ds.meta_data.uuid }}
        - name: provider-id
          value: metal3://{{ ds.meta_data.providerid }}
        - name: feature-gates
          value: AllAlpha=false
        - name: cgroup-driver
          value: systemd
        - name: container-runtime-endpoint
          value: unix:///var/run/crio/crio.sock
        - name: runtime-request-timeout
          value: 5m
        name: '{{ ds.meta_data.name }}'
    joinConfiguration:
      controlPlane: {}
      nodeRegistration:
        kubeletExtraArgs:
        - name: node-labels
          value: metal3.io/uuid={{ ds.meta_data.uuid }}
        - name: provider-id
          value: metal3://{{ ds.meta_data.providerid }}
        - name: feature-gates
          value: AllAlpha=false
        - name: cgroup-driver
          value: systemd
        - name: container-runtime-endpoint
          value: unix:///var/run/crio/crio.sock
        - name: runtime-request-timeout
          value: 5m
        name: '{{ ds.meta_data.name }}'
    postKubeadmCommands:
    - mkdir -p /home/kez/.kube
    - chown kez:kez /home/kez/.kube
    - cp /etc/kubernetes/admin.conf /home/kez/.kube/config
    - chown kez:kez /home/kez/.kube/config
    preKubeadmCommands:
    - rm /etc/cni/net.d/*
    - sed -i "s/MACAddressPolicy=persistent/MACAddressPolicy=none/g" /usr/lib/systemd/network/99-default.link
    - netplan apply
    - systemctl enable --now keepalived
    - sleep 30
    - systemctl enable --now crio
    - sleep 30
    - systemctl enable --now kubelet
    - sleep 120
    users:
    - name: kez
      passwd: $6$XXyZJ8BwjBrvzVOo$O7OoAQDRngVwNbeG7CjwUe.zUxktYPcLZ.JWUerfkc58jty6c86U9s2WqTuAMOSECK/ZOKnq8rzwMXlspKkrw.
      sshAuthorizedKeys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN65XT1iOqLGjTGwOHqKf4VtgOebCJzpbD80hGFvdts
        kez@ironcloud
      sudo: ALL=(ALL) NOPASSWD:ALL
  machineTemplate:
    spec:
      deletion:
        nodeDrainTimeoutSeconds: 0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: auto-openstack-infra-controlplane
  replicas: 1
  rollout:
    strategy:
      rollingUpdate:
        maxSurge: 1
  version: v1.35.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: auto-openstack-infra-controlplane
  namespace: metal3
spec:
  template:
    spec:
      dataTemplate:
        name: auto-openstack-infra-controlplane-template
      image:
        checksum: 3f574e954edb288a536eafa037d5d7313cb7dd542f8e5993a02d7ce202512457
        checksumType: sha256
        format: raw
        url: http://172.22.0.1/images/UBUNTU_24.04_NODE_IMAGE_K8S_v1.35.0-raw.img
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: auto-openstack-infra-controlplane-template
  namespace: metal3
spec:
  clusterName: auto-openstack-infra
  metaData:
    ipAddressesFromIPPool:
    - key: provisioningIP
      name: provisioning-pool
    objectNames:
    - key: name
      object: machine
    - key: local-hostname
      object: machine
    - key: local_hostname
      object: machine
    prefixesFromIPPool:
    - key: provisioningCIDR
      name: provisioning-pool
  networkData:
    links:
      ethernets:
      - id: eno1
        macAddress:
          fromHostInterface: eno1
        type: phy
      - id: eno2
        macAddress:
          fromHostInterface: eno2
        type: phy
    networks:
      ipv4:
      - id: externalv4
        ipAddressFromIPPool: externalv4-pool
        link: eno2
        routes:
        - gateway:
            fromIPPool: externalv4-pool
          network: 0.0.0.0
          prefix: 0
    services:
      dns:
      - 8.8.8.8
