apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: auto-openstack-infra
    nodepool: nodepool-0
  name: auto-openstack-infra
  namespace: baremetal-operator-system
spec:
  clusterName: auto-openstack-infra
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: auto-openstack-infra
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: auto-openstack-infra
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: auto-openstack-infra-workers
      clusterName: auto-openstack-infra
      deletion:
        nodeDrainTimeoutSeconds: 0
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: Metal3MachineTemplate
        name: auto-openstack-infra-workers
      version: v1.35.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: auto-openstack-infra-workers
  namespace: baremetal-operator-system
spec:
  template:
    spec:
      dataTemplate:
        name: auto-openstack-infra-workers-template
      image:
        checksum: 61895579cbb6dc579bd406ea5dc63d148d6714afd32976b9da3ea0daf5212d5a
        checksumType: sha256
        format: raw
        url: http://10.10.0.9/UBUNTU_24.04_NODE_IMAGE_K8S_v1.33.0-raw.img
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: auto-openstack-infra-workers-template
  namespace: baremetal-operator-system
spec:
  clusterName: auto-openstack-infra
  metaData:
    ipAddressesFromIPPool:
    - key: provisioningIP
      name: provisioning-pool
    objectNames:
    - key: name
      object: machine
    - key: local-hostname
      object: machine
    - key: local_hostname
      object: machine
    prefixesFromIPPool:
    - key: provisioningCIDR
      name: provisioning-pool
  networkData:
    links:
      ethernets:
      - id: eno1
        macAddress:
          fromHostInterface: eno1
        type: phy
      - id: eno2
        macAddress:
          fromHostInterface: eno2
        type: phy
    networks:
      ipv4:
      - id: externalv4
        ipAddressFromIPPool: externalv4-pool
        link: eno2
        routes:
        - gateway:
            fromIPPool: externalv4-pool
          network: 0.0.0.0
          prefix: 0
    services:
      dns:
      - 8.8.8.8
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: KubeadmConfigTemplate
metadata:
  name: auto-openstack-infra-workers
  namespace: baremetal-operator-system
spec:
  template:
    spec:
      files:
      - content: |
          network:
            version: 2
            renderer: networkd
            bridges:
              provisioning:
                interfaces: [eno1]
                addresses:
                - {{ ds.meta_data.provisioningIP }}/{{ ds.meta_data.provisioningCIDR }}
        owner: root:root
        path: /etc/netplan/52-ironicendpoint.yaml
        permissions: "0600"
      - content: |
          [registries.search]
          registries = ['docker.io']

          [registries.insecure]
          registries = ['10.10.0.9:5000']
        path: /etc/containers/registries.conf
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
          - name: node-labels
            value: metal3.io/uuid={{ ds.meta_data.uuid }}
          - name: provider-id
            value: metal3://{{ ds.meta_data.providerid }}
          - name: feature-gates
            value: AllAlpha=false
          - name: cgroup-driver
            value: systemd
          - name: container-runtime-endpoint
            value: unix:///var/run/crio/crio.sock
          - name: runtime-request-timeout
            value: 5m
          name: '{{ ds.meta_data.name }}'
      preKubeadmCommands:
      - sed -i "s/MACAddressPolicy=persistent/MACAddressPolicy=none/g" /usr/lib/systemd/network/99-default.link
      - netplan apply
      - systemctl enable --now crio
      - sleep 30
      - systemctl enable --now kubelet
      - sleep 120
      users:
      - name: kez
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFN65XT1iOqLGjTGwOHqKf4VtgOebCJzpbD80hGFvdts
          kez@ironcloud
        sudo: ALL=(ALL) NOPASSWD:ALL
