apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
  namespace: monitoring
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.object-storage.svc.cluster.local:9000
      access_key: admin
      secret_key: admin1010
      insecure: true
